### ISSUE TITLE
why is there no contrib component?

### ISSUE THREAD

**Issue by youxiaojie** [drtyhlpr/rpi23-gen-image#111]
# Use non-free Debian packages if needed
if [ "$ENABLE_NONFREE" = true ] ; then
  COMPONENTS="main,non-free"
fi

**Comment by drtyhlpr** [comment]
hi, because since 3 years noone asked for it :-) non-free is not contrib (i am sure you know). if there is a good reason to include contrib (even if its only due to your personal need) just tell me and I can add it ... or add it urself the script is pritty structured and adding a ENABLE_CONTRIB option by 90% copy and paste of ENABLE_NONFREE ... there you go :)

**Comment by drtyhlpr** [comment]
ah sorry now i see the error. yes contrib is added to apt sources at file 11-apt.sh but not in the 10-bootsrap.sh. fixed. thanks for report.
