### ISSUE TITLE
Severe console lag

### ISSUE THREAD

**Issue by mshelby** [drtyhlpr/rpi23-gen-image#61]
Successfully built for rpi3.
Gui works fluidly. No problems, but there is a severe lag in console activity. Both with keystroke input and with regular console activity such as executing a search within aptitude. The characters you type to search took a long time simply to show up after you type them.

Again, using aptitude as an example, it takes an inordinate amount of time to move from one highlighted file name to the next. but there is no lag in moving from one category to the next. Strange.

Also, it makes no difference whether the application is run from a terminal (within GUI) or from a console (tty2, etc...)

Is this a framebuffer issue> Has anyone encountered or solved this issue?

**Comment by drtyhlpr** [comment]
hi. sorry for the delay. I experienced similar problems some months ago https://github.com/drtyhlpr/rpi23-gen-image/issues/41. I only tested the serial and it was borken like hell - felt like a borken cable or such - with repeating characters etc. I did not find a solution. The problem was automagicly solved by time lol.
I was very pissed and I still dont trust systemd with that. I will do some test this weekend
